eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8764
spring:
  application:
    name: service-feign
feign:
  hystrix:
    enabled: true
#Feign是自带断路器的在D版本的Spring Cloud中它没有默认打开需要在配置文件中配置打开它