#服务名
spring:
  application:
    name: spring-cloud-eureka
#暴露的端口号
server:
  port: 8760
eureka:
  instance:
    hostname: peer2
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer3:8759/eureka/
#    fetch-registry: false
#    register-with-eureka: false
#本身也会被当做Client,所以false来表明自己是一个eureka server.
#只要有一条边将节点连接，就可以进行信息传播与同步


